import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import { Fragment } from 'react';
import styles from '../styles/Home.module.css'
import { Typography } from 'antd';

export default function Home() {
  const { Title } = Typography;

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Typography>
            <Title>
              Welcome to Arrimo Pro <br />
              Please ether login/register to continue
            </Title>
          </Typography>
        </div>
      </main>
    </Fragment>
  )
}
